name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'infra-as-code/**'  
      - 'lambda/**'          

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest

      - name: Run tests
        run: |
          pytest lambda/test_counter_function.py

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init
        working-directory: infra-as-code  

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra-as-code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'  
